smallcloudai/refact

self_hosting_machinery/webgui/selfhost_plugins.py
self_hosting_machinery/webgui/static/index.html
self_hosting_machinery/webgui/static/index.js

Changelist:
* when reloading the page, instead of being redirected to the default model-hosting pane you, will be kept on pane you were at before reloading
* navbar-brand redirects to the default pane: "model-hosting" instead of reloading
* history for visited panes that enables you to be redirected to prev pane on "go back" action in browser

Consistency for active-tab & history

---

database-start.sh

cassandra cannot start after container restarted, removing old pid file helps

container restart

---

refact_known_models/huggingface.py

We will not support codellama/7b model later:
* there are a lot of problems with codellama/7b implementation: bad FIM caps (possibly because of prompting), OOMs and errors while training process
* codellama/7b could be replaced with starcoder2 due to it's better performance

Codellama deprecation

---

refact_webgui/dashboards/dash_prime.py

The robot/human ratio percentage should range from 0 to 100 percent, not 0 to 1.

Fix percentage value range from 0 to 100

---

refact_known_models/passthrough.py
refact_utils/finetune/utils.py
refact_webgui/webgui/selfhost_fastapi_completions.py
refact_webgui/webgui/selfhost_model_assigner.py
refact_webgui/webgui/selfhost_queue.py
refact_webgui/webgui/selfhost_static.py
refact_webgui/webgui/static/tab-model-hosting.html
refact_webgui/webgui/static/tab-model-hosting.js
refact_webgui/webgui/static/tab-settings.html
refact_webgui/webgui/static/tab-settings.js
refact_webgui/webgui/tab_models_host.py
refact_webgui/webgui/tab_settings.py
setup.py

https://refact.fibery.io/Software_Development/New-document-428

Gemini Support

---

refact_utils/finetune/train_defaults.py
refact_webgui/webgui/static/tab-finetune.js
refact_webgui/webgui/tab_finetune.py

- make model_ctx_size default = 2048
- introducing more choices to the model_ctx_size at the finetuning stage

GPU OOM problem when finetuning fix

---

refact-agent/gui/src/components/ChatHistory/ChatHistory.tsx
refact-agent/gui/src/components/ChatRawJSON/ChatRawJSON.tsx
refact-agent/gui/src/components/Sidebar/Sidebar.tsx
refact-agent/gui/src/features/Chat/Thread/actions.ts
refact-agent/gui/src/features/Chat/Thread/reducer.ts
refact-agent/gui/src/features/History/historySlice.ts

Issue: https://refact.fibery.io/Software_Development/Sprint-2025-02-17-500#Task/Chat-fails-when-tried-to-open-old-chat-885
History items may or may not have `new_chat_suggested` on them.
To test.
build,
link to vscode
open an old chat.

fix(chat)): opening an old chat from history without the newer `suggested_chat` property.

---

refact-agent/gui/src/features/AgentUsage/AgentUsage.tsx
refact-agent/gui/src/hooks/useCapsForToolUse.ts

fix: making usage limits for all users

fix: making usage limits for all users

---

refact-agent/engine/src/tools/file_edit/auxiliary.rs
refact-agent/engine/src/tools/file_edit/tool_create_textdoc.rs
refact-agent/engine/src/tools/file_edit/tool_replace_textdoc.rs
refact-agent/engine/src/tools/file_edit/tool_update_textdoc.rs
refact-agent/engine/src/tools/file_edit/tool_update_textdoc_regex.rs

Fix textdoc tools to use get_file_text_from_memory_or_disk instead of read_to_string

Fix textdoc file reading

---

refact-agent/engine/README.md
refact-agent/engine/src/agentic/compress_trajectory.rs
refact-agent/engine/src/tools/mod.rs
refact-agent/engine/src/tools/scope_utils.rs
refact-agent/engine/src/tools/tool_locate_search.rs
refact-agent/engine/src/tools/tool_regex_search.rs
refact-agent/engine/src/tools/tool_relevant_files.rs
refact-agent/engine/src/tools/tool_search.rs
refact-agent/engine/src/tools/tools_description.rs
refact-agent/engine/src/yaml_configs/customization_compiled_in.yaml

- Introduce `ToolRegexSearch` to perform regex-based searches in specified file scopes.
- Integrate new tool into tools_description and tools module.
- Implement functionality for searching within entire workspace, specific directories, or individual files.
- Support case-sensitive searches and limit results with 'max_results' parameter.
- Provide detailed progress updates during search execution.
- Handle invalid regex patterns gracefully with error messages.

Regex search tool for pattern matching in files

---

refact-agent/gui/src/components/ChatForm/ToolConfirmation.tsx
refact-agent/gui/src/hooks/useSendChatRequest.ts

What changed.
Pressing `stop` in the tool confirmation window would stop the chat.
Now: pressing stop will call the lsp to get the `stop` reason message.

fix(tool confirmation): chat should continue if the user denies the tool use.

---

refact-agent/gui/src/components/Callout/Callout.module.css
refact-agent/gui/src/components/Callout/Callout.tsx
refact-agent/gui/src/components/IntegrationsView/IntegrationForm/ErrorState.tsx
refact-agent/gui/src/components/IntegrationsView/IntegrationForm/FormSmartlinks.tsx
refact-agent/gui/src/components/IntegrationsView/IntegrationsView.module.css
refact-agent/gui/src/components/IntegrationsView/IntegrationsView.tsx
refact-agent/gui/src/features/PatchesAndDiffsTracker/patchesAndDiffsTrackerSlice.ts

PR for this task: [Add "Open <integr_name>.yaml" button for not-erroring integration form](https://refact.fibery.io/Software_Development/Sprint-2025-02-24-516#Task/Add-Open-integr_name-.yaml-button-for-not-erroring-integration-form-924)

Add "Open <integr_name>.yaml" button for not-erroring integration form

---

refact-agent/gui/src/hooks/useCapsForToolUse.ts

Fixes: https://refact.fibery.io/Software_Development/Sprint-2025-02-24-516#Task/Model-gpt-4o-mini-is-not-available-for-selection-925
using array methods on a string causes gpt-4o and gpt-4o-mini to incorrectly match on caps selection.""
Accidentally committed on main, then reverted, and this reverts that one.

Revert "Revert "fix(model select): gpt-4o / gpt-4o-mini

---

refact-agent/gui/src/components/ChatForm/ChatForm.tsx

Fixes: https://refact.fibery.io/Software_Development/Sprint-2025-02-24-516#Task/Send-is-disabled-on-some-random-conditions-933
Also: https://refact.fibery.io/Software_Development/Sprint-2025-02-24-516#Task/Start-a-new-chat-tip-blocks-chat-too-early-898 if the blocking was the issue.
Caused by blocking the user from sending a messages when recommending they start a new chat.

fix: don't disable send when recommending to start a new chat.

---

refact-agent/engine/src/call_validation.rs
refact-agent/engine/src/http/routers/v1/at_tools.rs
refact-agent/engine/src/scratchpads/chat_passthrough.rs
refact-agent/engine/src/tools/tools_execute.rs
refact-agent/engine/tests/emergency_frog_situation/frog.py
refact-agent/gui/src/components/ChatForm/ToolConfirmation.tsx
refact-agent/gui/src/features/Chat/Thread/actions.ts
refact-agent/gui/src/features/Chat/Thread/reducer.ts
refact-agent/gui/src/features/PatchesAndDiffsTracker/patchesAndDiffsTrackerSlice.ts
refact-agent/gui/src/hooks/useSendChatRequest.ts
refact-agent/gui/src/services/refact/chat.ts

Ticket: https://refact.fibery.io/Software_Development/Sprint-2025-02-24-516#Task/Chat-suddenly-stops-if-it-was-manually-stopped-before-917
When pressing stop in the confirmation box, chat should stop. The frontend now adds the `tool` message.
Accept should still work the same.

refactor(tool confirmation): add rejection message client side, and remove `tool_confirmation` from chat paramters.

---

refact-agent/gui/src/components/ChatLinks/UncommittedChangesWarning.tsx

fixes: https://refact.fibery.io/Software_Development/Sprint-2025-02-24-516#Task/Agent-Git-warning-appears-on-some-random-conditions-934

fix(uncommitted changes warning): only show in agent mode and if message length is 0

---

refact-agent/gui/src/components/ChatForm/useCheckBoxes.ts

Fixes: https://refact.fibery.io/Software_Development/Sprint-2025-03-10-524#Task/UI-Cannot-attach-selected-lines,-checkbox-is-grey-963
Issue could be recreated by opening an old chat, interacting with the snippet checkbox, then changing the selection.

fix(selected snippet): snippet not updating when unchecked

---

refact-agent/gui/src/components/Tools/Texdoc.module.css
refact-agent/gui/src/components/Tools/Textdoc.tsx

changes the cursor to default while the allpy button is waiting for the network response, also changes the text to "diff" and removes the titles.

chore: change apply to diff and change the cursor to default.

---

refact-agent/gui/src/features/Chat/Thread/actions.ts
refact-agent/gui/src/features/Chat/Thread/reducer.ts
refact-agent/gui/src/hooks/useCapsForToolUse.ts
refact-agent/gui/src/hooks/useLinksFromLsp.ts

fixes: https://refact.fibery.io/Software_Development/Sprint-2025-03-10-524#Task/Error-bad-input,-n_ctx-4096,-max_new_tokens-4096-951
Cause of the issue: there's a smart link that would increment the max_new_tokens parameter passed to `/chat` the same info is also available from `/caps` and `/command-preview`.
The number from caps/preview seems to be more accurate.

fix(chat request): set max tokens for the model

---

refact-agent/gui/src/features/Chat/Thread/actions.ts
refact-agent/gui/src/features/Chat/Thread/reducer.ts
refact-agent/gui/src/hooks/useCapsForToolUse.ts
refact-agent/gui/src/hooks/useLinksFromLsp.ts

Reverts smallcloudai/refact#600
May have introduced a regression where tool calls end up like this when using explore mode + gpt-4
```
"{\"symbol\":\"Frog\"}{\"query\":\"struct Frog\",\"scope\":\"workspace\"}{\"query\":\"struct Frog\",\"scope\":\"workspace\"}{\"query\":\"struct Frog\",\"scope\":\"workspace\"}"
```

Revert "fix(chat request): set max tokens for the model"

---

refact-agent/gui/src/components/ChatForm/ChatForm.tsx

issue:
When the user has not interacted with the checkboxes and begins typing the values do not update when they select other snippets.

fix: change boxes after the user has started typing but not interacted with the checkboxes

---

refact-agent/gui/src/components/ChatForm/ChatControls.tsx
refact-agent/gui/src/components/ChatForm/ChatForm.test.tsx
refact-agent/gui/src/components/ChatForm/ChatForm.tsx
refact-agent/gui/src/components/ChatForm/useCheckBoxes.ts
refact-agent/gui/src/components/ChatForm/useCommandCompletionAndPreviewFiles.ts
refact-agent/gui/src/components/ChatForm/utils.ts
refact-agent/gui/src/components/Dropzone/Dropzone.tsx
refact-agent/gui/src/components/Dropzone/index.tsx
refact-agent/gui/src/events/index.ts
refact-agent/gui/src/hooks/index.ts
refact-agent/gui/src/hooks/useEventBusForApp.ts

Ticket: https://refact.fibery.io/Software_Development/Sprint-2025-03-24-530#Task/UI-Attach-multiple-files-976
First task only.
Changes the attach file check box to a button.
Also: active file is no longer attached by default.
To test: compile and run in vscode to see the button

wip: remove attach file checkbox.

---

refact-agent/engine/src/agentic/compress_trajectory.rs
refact-agent/engine/src/agentic/generate_commit_message.rs
refact-agent/engine/src/agentic/generate_follow_up_message.rs
refact-agent/engine/src/at_commands/at_commands.rs
refact-agent/engine/src/autonomy.rs
refact-agent/engine/src/http/routers/v1/at_commands.rs
refact-agent/engine/src/http/routers/v1/at_tools.rs
refact-agent/engine/src/http/routers/v1/chat.rs
refact-agent/engine/src/http/routers/v1/code_completion.rs
refact-agent/engine/src/http/routers/v1/links.rs
refact-agent/engine/src/http/routers/v1/subchat.rs
refact-agent/engine/src/tools/tool_create_memory_bank.rs
refact-agent/engine/src/tools/tool_deep_analysis.rs
refact-agent/engine/src/tools/tool_locate_search.rs
refact-agent/engine/src/tools/tool_relevant_files.rs

current_model in ccx doesn't set up
so if we dont have some subchat model we'll fallback to "" instead of actual chat_model

current model fallback setup

---

refact-agent/gui/src/components/ChatForm/RetryForm.tsx
refact-agent/gui/src/components/ChatLinks/ChatLinks.tsx

ticket: https://refact.fibery.io/Software_Development/Sprint-2025-04-21-569#Task/Bug---Follow-up-links-are-not-clickable---while-user-has-coins-1105

fix: disable chat links when balance is low.

---

refact-agent/gui/src/components/ChatForm/ChatControls.tsx

With conversion rate 10$ = 10k coins, we should show corresponding values per million tokens as how different providers do

Fix: format coins pricing

---

refact-agent/gui/src/components/ChatForm/ChatControls.tsx
refact-agent/gui/src/components/ChatForm/ChatForm.tsx
refact-agent/gui/src/components/ChatForm/PromptSelect.tsx
refact-agent/gui/src/components/Select/Select.tsx

- if there is only 1 default sys prompt - don’t show sys prompts selector  
-  Added “add model” option to models selector - which leads to Providers page -
- Also - removed duplicated selected model - we had one in textarea of chat form and another one selected in the bottom (chat controls)

model list, system prompt list

---

refact-agent/gui/src/components/UsageCounter/UsageCounter.tsx
refact-agent/gui/src/features/Chat/Thread/utils.test.ts
refact-agent/gui/src/features/Chat/Thread/utils.ts
refact-agent/gui/src/services/refact/chat.ts
refact-agent/gui/src/services/refact/types.ts
refact-agent/gui/src/utils/calculateUsageInputTokens.ts

openai response stream can have `choices: []` with usage.

fix(usage): handle open ai usage with `choices: []`

---

refact-agent/gui/src/components/ChatContent/ChatContent.tsx

fixes: https://refact.fibery.io/Software_Development/Sprint-2025-05-05-579#Task/UI---Often-no-Stop-button-in-chat-1125
issue: Stop button doesn't show while waiting for a response.

fix: stop button not showing while waiting for response.

---

refact-agent/engine/src/http/routers.rs

https://refact.fibery.io/Software_Development/Sprint-2025-02-24-516#Task/Payload-Too-Large-issue-593

engine: increase payload limit from 2mb to 15mb

---

refact-agent/engine/python_binding_and_cmdline/setup.py

This small PR resolves the `re` deprecation warnings:
```python
DeprecationWarning: 'count' is passed as positional argument
```

Resolve deprecation warnings of regex library

---

refact-agent/gui/src/components/Sidebar/GroupTree/ConfirmGroupSelection/ConfirmGroupSelection.module.css
refact-agent/gui/src/components/Sidebar/GroupTree/GroupTree.module.css
refact-agent/gui/src/components/Sidebar/GroupTree/GroupTree.tsx
refact-agent/gui/src/components/Sidebar/GroupTree/useGroupTree.ts
refact-agent/gui/src/components/Sidebar/Sidebar.tsx
refact-agent/gui/src/components/Toolbar/Dropdown.tsx
refact-agent/gui/src/services/refact/caps.ts

Fixes this one:
https://refact.fibery.io/Software_Development/Task/Bug---Group-tree-is-not-being-rendered-from-time-to-time-1168
https://refact.fibery.io/Software_Development/Task/Bug---select-workspace-only-if-caps.metadata-supports-it-1167

Fix: visibility of group tree & passthrough if caps.metadata.features doesn't contain knowledge

---

refact-agent/gui/src/__fixtures__/msw.ts
refact-agent/gui/src/__tests__/StartNewChat.test.tsx
refact-agent/gui/src/components/Sidebar/Sidebar.tsx
refact-agent/gui/src/components/Toolbar/Dropdown.tsx
refact-agent/gui/src/components/Toolbar/Toolbar.tsx
refact-agent/gui/src/hooks/useActiveTeamsGroup.ts

Fixes these:
https://refact.fibery.io/Software_Development/Task/bug---Creating-new-chat-button-is-disabled-for-Free-Pro-users-1170

Fix: Active Teams Group state management

---

refact-agent/gui/src/components/ChatContent/ToolsContent.tsx
refact-agent/gui/src/components/ChatForm/ChatForm.tsx
refact-agent/gui/src/features/Chat/Chat.tsx
refact-agent/gui/src/features/Chat/Thread/reducer.ts
refact-agent/gui/src/features/Chat/Thread/selectors.ts
refact-agent/gui/src/hooks/useSendChatRequest.ts

Fixes the stop button,
(prevent send was being reset when `doneStreaming` causing issues)
refactored `autoSend` so the dependencies for `useEffect` change less often (causing the hook to trigger).
How to test..
Ask a questoin like `call tree` wait until the tool call is on screen and press `stop`... change the timing a few times and it should stop and stay stoped.

Prevent send fix
