smallcloudai/refact

- refact_scratchpads/scratchpad_hf.py
Two most important ones:
* strip() + "\n\n"
* delete space after "ASSISTANT:"
> WizardLM 13b fixes

- refact_data_pipeline/__init__.py
- refact_data_pipeline/datadef.py
There are some changes which are accidentally not in the main branch yet
Training stuff related
> DatasetDumpedDef in `find_dataset_def`

- self_hosting_machinery/watchdog/docker_watchdog.py
Tested scenario:
* add 1.6b, 7b
* let it settle
* delete 1.6b
* 7b moves from gpu1 to gpu0
* should not compile again on gpu0, because it has already compiled for gpu1
(bug found on 8 gpu machine)
> Watchdog compiles each model once for all GPUs

- refact_data_pipeline/finetune/process_uploaded_files.py
- self_hosting_machinery/webgui/static/components/modals/modal-upload-files.js
- self_hosting_machinery/webgui/static/tab-finetune.html
- self_hosting_machinery/webgui/static/tab-finetune.js
- self_hosting_machinery/webgui/static/tab-upload.html
- self_hosting_machinery/webgui/static/tab-upload.js
- self_hosting_machinery/webgui/tab_loras.py
- self_hosting_machinery/webgui/tab_upload.py
- self_hosting_machinery/webgui/webgui.py
- setup.py
* Added reusable "Upload Files Modal" component
* Sources: replaced "upload files and upload link" with the component
* Finetune: added "Upload lora btn" that lets you upload your custom lora via link or file input
> Lora upload & Upload enhancements

- self_hosting_machinery/webgui/static/tab-finetune.html
the line "Optional. If not specified, the default branch will be used. " must have been copied from /webgui/static/tab-upload.html. It is not related to finetuning
> remove unrelated message

- refact_scratchpads_no_gpu/stream_results.py
- refact_scratchpads_no_gpu/stream_results_async.py
- self_hosting_machinery/inference/inference_hf.py
Fixes https://github.com/smallcloudai/refact/issues/207
> Support for HTTP_PROXY

- self_hosting_machinery/inference/inference_hf.py
Possibly fixes
https://github.com/smallcloudai/refact-lsp/issues/40
(someone needs to check)
> do_sample = temperature >= 0.05

- Dockerfile
- known_models_db/refact_known_models/huggingface.py
- known_models_db/refact_known_models/refact.py
- self_hosting_machinery/webgui/selfhost_fastapi_completions.py
- self_hosting_machinery/webgui/selfhost_model_assigner.py
- setup.py
Added 6 new chat models:
* magicoder/6.7b
* mistral/7b/instruct-v0.1
* mixtral/8x7b/instruct-v0.1
* phind/34b/v2
* deepseek-coder/6.7b/instruct
* deepseek-coder/33b/instruct
> New chat models

- README.md
* AI Toolbox column deleted
* 5 new models added
* update on usage: start server with docker compose
> Readme update 1 3

- self_hosting_machinery/finetune/modelling/flash_sa.py
- self_hosting_machinery/inference/inference_hf.py
Disabling mem efficient sdp fix problems with torch
> Inference and finetune for <8.0 cuda caps gpus

- Dockerfile
- README.md
- database-start.sh
- docker-entrypoint.sh
* /perm_storage/cassandra for cassandra data and logs
* move previous cassandra data and logs into it if exist
* cassandra configuration of working paths and memory consumtion
* start service if it's not working
> Cassandra fixes

- refact_webgui/dashboards/dash_prime.py
- refact_webgui/dashboards/utils.py
- refact_webgui/webgui/selfhost_database.py
- refact_webgui/webgui/selfhost_statistics.py
- refact_webgui/webgui/static/dashboards/dash_prime.js
- refact_webgui/webgui/static/dashboards/dash_users.js
- refact_webgui/webgui/static/dashboards/plots.js
Changelist:
Summary tab:
* changed order of plots
* Assistant -> Refact
* table limit to top-20
* ignore some plugin versions in statistic; added message on bottom; should appear only when all plots have been rendered
Users tab:
* activating all users by default
> Dashboard Improvements

- refact_webgui/webgui/static/style.css
- refact_webgui/webgui/static/tab-model-hosting.html
- refact_webgui/webgui/static/tab-model-hosting.js
- refact_webgui/webgui/static/utils/tab-model-hosting-utils.js
> Finetune Assignment Redesign

- refact_utils/finetune/utils.py
- refact_webgui/webgui/static/style.css
- refact_webgui/webgui/static/tab-finetune.js
- refact_webgui/webgui/static/tab-model-hosting.js
- refact_webgui/webgui/static/utils/tab-model-hosting-utils.js
- refact_webgui/webgui/static/utils/utils.js
- refact_webgui/webgui/tab_finetune.py
> New Loras Rename

- refact_utils/finetune/utils.py
- refact_webgui/webgui/selfhost_fastapi_completions.py
merge after base docker rebuild
> version check fix

- Dockerfile
- Dockerfile.base
- setup.py
Requires update torch to 2.2.1
> auto-gptq version up

- refact_known_models/passthrough.py
- refact_utils/finetune/utils.py
- refact_webgui/webgui/selfhost_fastapi_completions.py
- refact_webgui/webgui/static/tab-model-hosting.html
* revise 3rd party models
* caps_version for chat completions
* some UI fixes
> 3rdparty fixes 20 12 24

- Dockerfile.base
* update to v0.6.6.post1
* fix LoRA loading
* fix refact model's attention
> update refact to refact_v0.6.6.post1_2339d59

- refact-agent/engine/src/known_models.rs
- refact-agent/engine/src/scratchpads/chat_passthrough.rs
- refact-agent/gui/src/hooks/useCapsForToolUse.ts
Enable reasoning support for models and remove filtering in hook
> Reasoning models support for being chat models

- refact-agent/engine/src/caps.rs
- refact-agent/gui/src/__fixtures__/caps.ts
- refact-agent/gui/src/components/ChatForm/ChatControls.tsx
- refact-agent/gui/src/components/ChatForm/PromptSelect.tsx
- refact-agent/gui/src/hooks/useCapsForToolUse.ts
- refact-agent/gui/src/services/refact/caps.ts
* ordered chat models list
* default system prompt pass
> UI fixes 19 02 25

- refact-agent/engine/src/vecdb/vdb_highlev.rs
- refact-agent/engine/src/vecdb/vdb_sqlite.rs
Handle malformed database by removing and reinitializing vecdb
> vecdb malformed fix

- .github/workflows/agent_gui_npm_publish.yml
> ci: disable automatic version bump if pushing to main

- refact-agent/gui/src/app/middleware.ts
- refact-agent/gui/src/services/refact/types.ts
To test:
Logout from `smallcloud.ai`
Login in with a free tier account.
Copy the api.
Start the lsp using that apikey. `-k [api key]`
Pick and agentic model, 
Send a few messages.
> WIP: fix(agent usage): `refact_agent_...` may or may not be on `ChatResponse` type.

- refact-agent/gui/src/components/ChatContent/ChatContent.tsx
Add sonnet to do something to a file that take some time.
```
rewrite this @file refact-agent/gui/README.md and add some puns.
```
> fix(ui): show ... spinner while waiting for response.

- refact-agent/gui/src/components/ChatForm/FilesPreview.tsx
- refact-agent/gui/src/components/ChatForm/useCommandCompletionAndPreviewFiles.ts
- refact-agent/gui/src/components/UsageCounter/UsageCounter.tsx
- refact-agent/gui/src/features/Chat/Thread/actions.ts
- refact-agent/gui/src/features/Chat/Thread/reducer.ts
- refact-agent/gui/src/features/History/historySlice.ts
- refact-agent/gui/src/services/refact/chat.ts
- refact-agent/gui/src/services/refact/commands.ts
- refact-agent/gui/src/utils/formatNumberToFixed.ts
Fixes: https://refact.fibery.io/Software_Development/Task/Chat-title-generation-not-working-with-Sonnet-3.7-919
https://refact.fibery.io/Software_Development/Task/Context-size-limit-is-decreasing-somehow-936
> fix: debouncing at-command-preview & formatting messages for LSP

- refact-agent/engine/src/scratchpads/chat_utils_limit_history.rs
`cargo test test_chatlimit -- --nocapture`
> Fix anthropic first message

- refact-agent/gui/src/components/ChatLinks/ChatLinks.tsx
Shows chat links in all modes.
> feat(chat links): show links in all modes.

- refact-agent/engine/src/main.rs
Ensure cache and config directories are created on first start
> First start fix

- .gitignore
- refact-agent/gui/src/components/ChatContent/ChatContent.module.css
- refact-agent/gui/src/components/ChatContent/ToolsContent.tsx
- refact-agent/gui/src/components/Command/Markdown.tsx
- refact-agent/gui/src/components/Command/index.tsx
- refact-agent/gui/src/components/Reveal/Reveal.tsx
Fixes: https://refact.fibery.io/Software_Development/Sprint-2025-03-10-524#Task/Hide-details-doesn't-work-well-961
> Fix tool call reveal scroll

- refact-agent/gui/src/components/ChatContent/ChatContent.tsx
- refact-agent/gui/src/hooks/index.ts
- refact-agent/gui/src/hooks/useCheckpoints.ts
- refact-agent/gui/src/hooks/useDiffFileReload.ts
- refact-agent/gui/src/hooks/useEventBusForIDE.ts
Implements this task: https://refact.fibery.io/Software_Development/Task/JetBrains-UI-Force-reload-files-on-updates-by-Agent-984
> Improvement: Force reload of files for JetBrains

- refact-agent/gui/.storybook/preview.tsx
- refact-agent/gui/src/components/Chat/Chat.stories.tsx
- refact-agent/gui/src/components/ChatContent/ChatContent.module.css
- refact-agent/gui/src/components/ChatContent/ChatContent.tsx
- refact-agent/gui/src/components/ChatContent/UserInput.tsx
- refact-agent/gui/src/components/ChatContent/useAutoScroll.ts
- refact-agent/gui/src/components/ScrollArea/ScrollArea.stories.tsx
- refact-agent/gui/src/components/ScrollArea/ScrollAreaWithAnchor.stories.tsx
- refact-agent/gui/src/components/ScrollArea/ScrollAreaWithAnchor.tsx
- refact-agent/gui/src/components/ScrollArea/index.ts
- refact-agent/gui/src/hooks/index.ts
- refact-agent/gui/src/hooks/useResizeObserver.ts
- refact-agent/gui/src/utils/test-setup.ts
adds extra space to the bottom of the chat content so that the user message is at the top of the screen.
ticket: https://refact.fibery.io/Software_Development/Sprint-2025-03-10-524#Task/UI-Better-scroll-move-role-user-up,-fill-progressively-empty-space-974
How to test:
ask questions and open chats.
The last user message should be at the top of the screen.
> WIP: User message space

- refact-agent/gui/src/components/Buttons/FadedButton.tsx
- refact-agent/gui/src/components/Buttons/button.module.css
- refact-agent/gui/src/components/Buttons/index.tsx
- refact-agent/gui/src/components/ChatContent/DiffContent.tsx
- refact-agent/gui/src/components/ChatContent/ToolsContent.tsx
ticket: https://refact.fibery.io/Software_Development/Sprint-2025-03-10-524#Task/UI-knowledge-985
> Knowledge UI changes

- refact-agent/engine/src/tools/tool_mv.rs
- refact-agent/engine/src/tools/tool_rm.rs
- refact-agent/gui/src/components/ChatContent/DiffContent.tsx
- refact-agent/gui/src/hooks/useDiffFileReload.ts
Updated result of `mv` tool:
Updated result of `rm` tool:
> Improvement: rm, mv tools return diff message to the UI

- refact-agent/gui/src/components/ChatContent/DiffContent.tsx
- refact-agent/gui/src/components/ChatContent/ToolsContent.tsx
- refact-agent/gui/src/components/Reveal/Reveal.tsx
- refact-agent/gui/src/components/ScrollArea/ScrollAreaWithAnchor.stories.tsx
- refact-agent/gui/src/components/Tools/Textdoc.tsx
- refact-agent/gui/src/hooks/index.ts
- refact-agent/gui/src/hooks/useHideScroll.ts
Fixes: https://refact.fibery.io/Software_Development/Sprint-2025-03-10-524#Task/Scroll-position-not-maintained-when-hiding-diff-content-999
> Scroll when clicking hide button for diffs, and knowledge.

- refact-agent/gui/src/components/ChatForm/ChatForm.tsx
- refact-agent/gui/src/hooks/index.ts
- refact-agent/gui/src/hooks/useAutoFocusOnce.ts
fixes: https://refact.fibery.io/Software_Development/Sprint-2025-03-10-524#Task/UI-Input-box-steals-focus-997
> fix: only autoFocus on chat input once.

- refact-agent/gui/src/__fixtures__/markdown-issue.ts
- refact-agent/gui/src/components/ChatForm/ChatForm.tsx
- refact-agent/gui/src/components/ChatForm/SuggestNewChat/SuggestNewChat.tsx
- refact-agent/gui/src/components/ScrollArea/FollowButton.tsx
- refact-agent/gui/src/components/ScrollArea/ScrollAreaWithAnchor.tsx
- refact-agent/gui/src/components/UsageCounter/useUsageCounter.ts
- refact-agent/gui/src/features/Chat/Thread/actions.ts
- refact-agent/gui/src/features/Chat/Thread/reducer.ts
- refact-agent/gui/src/features/Chat/Thread/types.ts
- refact-agent/gui/src/hooks/useCompressChat.ts
- refact-agent/gui/src/hooks/useSendChatRequest.ts
Task: https://refact.fibery.io/Software_Development/Sprint-2025-03-10-524#Task/UI-compresion-986
and
https://refact.fibery.io/Software_Development/Sprint-2025-03-10-524#Task/Cannot-assign-to-read-only-property-'wasSuggested'-error-when-opening-chat-history-1001
> Compress and continue

- refact-agent/gui/src/components/Chat/Chat.tsx
`textare.focus` was being called on stream end grabbing the cursor from the ide.
> fix: focus being called when stream ends.

- refact-agent/gui/src/components/ChatContent/ToolsContent.tsx
When clicking `hide details` the text bellow the tool call should still be on screen
> fix: scroll when hiding tool calls.

- refact-agent/gui/src/components/Toolbar/Dropdown.tsx
- refact-agent/gui/src/hooks/useAgentUsage.ts
> Feature: Daily messages shown in Dropdown

- refact-agent/gui/src/components/ChatContent/ToolsContent.tsx
Forgot to pass the ref to the dom so knowledge scrolls when it collapses.
> fix: forgot to pass the ref to the dom for knowledge hide button

- refact-agent/gui/src/components/ChatContent/UserInput.tsx
- refact-agent/gui/src/components/ChatForm/ChatForm.tsx
- refact-agent/gui/src/components/ChatForm/SuggestNewChat/SuggestNewChat.tsx
- refact-agent/gui/src/hooks/useCompressChat.ts
Ticket: https://refact.fibery.io/Software_Development/Sprint-2025-03-24-530#Task/UI-Compression-usability-1021
> change the ui for compressed messages and fix shared loading states.

- refact-agent/gui/src/app/middleware.ts
- refact-agent/gui/src/hooks/useGetPing.ts
- refact-agent/gui/src/services/refact/ping.ts
Fixes this task:
https://refact.fibery.io/Software_Development/Task/Bug-VSCode-wrong-port-958
> Fix: Proper LSP port invalidation

- refact-agent/gui/src/app/middleware.ts
- refact-agent/gui/src/components/Chat/Chat.tsx
- refact-agent/gui/src/components/ChatForm/SuggestNewChat/SuggestNewChat.tsx
- refact-agent/gui/src/components/UsageCounter/useUsageCounter.ts
- refact-agent/gui/src/features/Chat/Thread/reducer.ts
- refact-agent/gui/src/features/Chat/Thread/selectors.ts
- refact-agent/gui/src/features/Chat/Thread/types.ts
- refact-agent/gui/src/hooks/useCompressionStop.ts
- refact-agent/gui/src/hooks/useDiffFileReload.ts
- refact-agent/gui/src/hooks/useEventBusForIDE.ts
- refact-agent/gui/src/hooks/useSendChatRequest.ts
adds a force reload event for JB file system when a tool message comes in
TBD: should we do this with the diffs as well?
works with: https://github.com/smallcloudai/refact-intellij/pull/248
Also fixes an issue where compression would stop the chat,
> add forceReload event on any tool result.

- refact-agent/gui/src/components/Tour/TourEnd.tsx
> fix: tour link colour in light mode

- refact-agent/gui/src/components/ChatForm/ChatControls.tsx
- refact-agent/gui/src/components/ChatForm/ChatForm.module.css
- refact-agent/gui/src/components/ChatForm/ChatForm.tsx
- refact-agent/gui/src/components/TextArea/TextArea.tsx
- refact-agent/gui/src/components/UsageCounter/UsageCounter.tsx
Ticket: https://refact.fibery.io/Software_Development/Sprint-2025-04-21-569#Task/UI-Model-switch-as-drop-down-list-inside-the-text-box-1020
> UI move model select

- refact-agent/gui/src/components/ChatContent/ChatContent.stories.tsx
- refact-agent/gui/src/components/ChatContent/ToolsContent.tsx
- refact-agent/gui/src/components/Text/AnimatedText.module.css
- refact-agent/gui/src/components/Text/AnimatedText.stories.tsx
- refact-agent/gui/src/components/Text/AnimatedText.tsx
- refact-agent/gui/src/components/Text/index.ts
Add loading state to tool calls.
> ui(tool calls): animate tool calls

- refact-agent/gui/src/components/ChatForm/ChatForm.module.css
- refact-agent/gui/src/components/ChatForm/ChatForm.tsx
- refact-agent/gui/src/components/TextArea/TextArea.tsx
Fixes the textarea cursor hiding behind the caps select.
> Fix caps select hiding text

- refact-agent/gui/src/components/ChatContent/ToolsContent.tsx
- refact-agent/gui/src/features/Chat/Thread/selectors.ts
ticket: https://refact.fibery.io/Software_Development/Task/UI-rm-tool-when-is-finished,-it-running-loading-animation-1099
> fix: tool not resolved when it's a diff.

- refact-agent/gui/src/components/Callout/Callout.tsx
Ticket: https://refact.fibery.io/Software_Development/Sprint-2025-04-21-569#Task/bug---Top-up-and-doc-links-not-opening-due-to-sandbox-restrictions-1106
> fix: open links in vscode

- refact-agent/gui/src/components/ChatForm/ChatControls.tsx
- refact-agent/gui/src/components/Select/Select.tsx
position cost hover card, only show when disabled and and cost in coins
> small fixes and tweaks.

- refact-agent/gui/src/components/ChatForm/ChatControls.tsx
- refact-agent/gui/src/components/ChatForm/ChatForm.tsx
- refact-agent/gui/src/components/ChatForm/useCheckBoxes.ts
adds a lock icon for when selected snippet stops changing.
locks selected snippet when the user starts typing in the textarea.
> ui(selected snippet): set interacted to true when typing and add a lock icon.

- refact-agent/gui/src/__tests__/DeleteChat.test.tsx
- refact-agent/gui/src/components/Select/Select.tsx
fixes: https://refact.fibery.io/Software_Development/Sprint-2025-05-05-579#Task/Bug-when-showing-the-prices-1121
> fix: double popover on select

- refact-agent/gui/src/hooks/useSendChatRequest.ts
> fix(ui): onAbort not being called when clicking the stop button.

- refact-agent/engine/src/files_correction.rs
- refact-agent/engine/src/files_correction_cache.rs
- refact-agent/engine/src/files_in_workspace.rs
- refact-agent/engine/src/main.rs
Rebased https://github.com/smallcloudai/refact/pull/715
TODO:
* slow and memory inefficient tree
* windows!!!
What else:
* fuzzy search possible improvements
* top n optimizations in find matches and so on
> Files correction cache 21 05 25

- refact-agent/engine/src/background_tasks.rs
- refact-agent/engine/src/files_in_workspace.rs
- refact-agent/engine/src/git/checkpoints.rs
- refact-agent/engine/src/git/operations.rs
- refact-agent/engine/src/global_context.rs
- refact-agent/engine/src/http/routers/v1/git.rs
- refact-agent/engine/src/main.rs
abort slow git sync commands using a flag
> Checkpoints abort 30 05 25

- refact-agent/engine/src/scratchpads/chat_passthrough.rs
- refact-agent/engine/src/subchat.rs
Here is 2 problems:
* we don't have subchat model in models list => we should use correct params and n_ctx for fallback model
* in case of no tool calls in last message from subchat we shouldn't fail
> subchat model params and chat id fixes
